name: Build and Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: CalicotEncheres/

      - name: Build Application
        run: dotnet build --configuration Release --no-restore
        working-directory: CalicotEncheres/

      - name: Publish Application
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish
        working-directory: CalicotEncheres/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-calicot-dev-2
          package: ${{ github.workspace }}/publish
